baseURL = 'https://ai-safety-awareness-foundation.github.io/aisaf/'
languageCode = 'en-US'
title = 'The AI Safety Awareness Foundation'

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 20

[[menus.main]]
name = 'Tags'
pageRef = '/tags'
weight = 30

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
