name: Auto Set Past Workshops temporalstatus to Past

on:
  schedule:
    # Runs at 00:00 UTC every day
    - cron: '0 0 * * *'
  # Allow manual triggering
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  update-and-commit:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # We need to grab the entirety of git history so that we can create a
          # commit and push back to upstream
          fetch-depth: 0
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Run updater script
        run: python scripts/updater.py
      
      - name: Check for changes
        id: git-check
        run: |
          git diff --exit-code || echo "has_changes=true" >> $GITHUB_OUTPUT
      
      - name: Commit changes
        if: steps.git-check.outputs.has_changes == 'true'
        run: |
          git config --local user.email "github-actions@github.com"
          git config --local user.name "GitHub Actions"
          git add -A
          git commit -m "Auto update of temporalstatus via GitHub Actions"
          git push
  deploy-after-update:
    needs: update-and-commit
    uses: ./.github/workflows/hugo.yml
